apiVersion: v1
kind: Secret
metadata:
  name: api-medico-secret
  #namespace: default
type: Opaque
data:
  MedicoConnectionString: U2VydmVyPXNxbHNlcnZlcmRiO0RhdGFiYXNlPU1lZGljb0RiO1VzZXI9U0E7UGFzc3dvcmQ9RklBUENvbm5fUGFzczEyMyM7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO0VuY3J5cHQ9RmFsc2U7
