apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-latest
  # namespace: fiap
  labels:
    app: api-gateway-latest
  annotations:
    autor: "Grupo 23"
    app-version: "4.0"
    description: "API responsavel pelo gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-latest
  template:
    metadata:
      labels:
        app: api-gateway-latest
    spec:
      containers:
        - image: somdesp/healthmed:api_gateway_latest
          name: api-gateway-latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-latest
  # namespace: fiap
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: api-gateway-latest
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-latest
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
