apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_agendamento_latest
  # namespace: fiap
  labels:
    app: api_agendamento_latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api_agendamento_latest
  template:
    metadata:
      labels:
        app: api_agendamento_latest
    spec:
      containers:
        - image: somdesp/healthmed:api_agendamento_latest
          name: api_agendamento_latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: ConnectionStrings__AgendamentoConnectionString
              valueFrom:
                secretKeyRef:
                  name: api-agendamento-secret
                  key: AgendamentoConnectionString

            - name: ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: apiserver-configmap
                  key: RabbitMq

---
apiVersion: v1
kind: Service
metadata:
  name: api_agendamento_latest
  # namespace: fiap
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30083
  selector:
    app: api_agendamento_latest
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api_agendamento_latest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api_agendamento_latest
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
