apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-latest
  # namespace: fiap
  labels:
    app: auth-latest
  annotations:
    autor: "Grupo 23"
    app-version: "4.0"
    description: "API responsavel pelo login"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-latest
  template:
    metadata:
      labels:
        app: auth-latest
    spec:
      containers:
        - image: somdesp/fiap5:auth_latest
          name: auth-latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: ConnectionStrings__FiapConnection
              valueFrom:
                secretKeyRef:
                  name: apiserver-secret
                  key: FiapConnection

            - name: ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: apiserver-configmap
                  key: RabbitMq

---
apiVersion: v1
kind: Service
metadata:
  name: auth-latest
  # namespace: fiap
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30081
  selector:
    app: auth-latest
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-latest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-latest
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
