apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "techchallenge"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["api-consult-latest:8080", "api-creation-latest:8080", "api-deletion-latest:8080", "api-update-latest:8080"]
