apiVersion: v1
kind: PersistentVolume
metadata:
  name: bd-healthmed-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/d/vol/bd
