kind: Secret
apiVersion: v1
metadata:
  name: rabbitmq-cluster-deployment-default-user
  namespace: fiap
stringData:
  default_user.conf: |
    default_user = guest
    default_pass = guest
  password: guest
  username: guest
type: Opaque
