apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-latest
  labels:
    app: ui-app-latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-app-latest
  template:
    metadata:
      labels:
        app: ui-app-latest
    spec:
      containers:
        - name: ui-app-latest
          image: somdesp/healthmed:ui_app_latest
          ports:
            - containerPort: 80 # Corrigido de 8080 para 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ui-app-latest-service
  labels:
    app: ui-app-latest
spec:
  type: NodePort
  selector:
    app: ui-app-latest
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
